name: Build

on:
  push:
    tags:
      - '*' # Triggers the workflow when you push a tag starting with 'v' (e.g., v1.0.0)

permissions:
  contents: write # Required permission to create a GitHub Release

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v7

      - name: Setup Node.js Environment
        uses: actions/actions/setup-node@v7
        with:
          node-version: 22 # Specifies your project's Node version
          cache: 'npm'

      - name: Install Project Dependencies
        run: npm ci # Performs a clean, automated install of package-lock.json

      - name: Run Build Script
        run: npm run build # Generates the production bundle (typically in a 'dist' or 'build' folder)

      - name: make release
        id: make_release
        uses: softprops/action-gh-release@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref }}
          name: LonkOS ${{ github.ref_name }}
          draft: true
          prerelease: false
          fail_on_unmatched_files: true
          files: |
            LonkOS.url
            LonkOS.html
