name: Continuous Build

on:
  push:
    paths-ignore:
    - 'README.md'
    - '.github/workflows/cbuild.yml'
    - '.github/workflows/wbuild.yml'
    - '.github/workflows/build.yml'
  pull_request:
    paths-ignore:
    - 'README.md'
    - '.github/workflows/cbuild.yml'
    - '.github/workflows/wbuild.yml'
    - '.github/workflows/build.yml'
jobs:
  continuous-build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Set Release Name
        id: vars
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "RELEASE_NAME=${{ github.event.inputs.release_name }}" >> $GITHUB_ENV
          else
            echo "RELEASE_NAME=${{ github.ref_name }}" >> $GITHUB_ENV
          fi
          
      - name: Build project
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            npm run build -- `${ github.event.inputs.release_name }`
          else
            npm run build -- `${ github.ref_name }`
          fi

      - name: Rename Outputs
        run: |
          mv ./builds/LonkOS.html ./builds/LonkOS-${{ env.RELEASE_NAME }}.html
          mv ./builds/LonkOS.url ./builds/LonkOS-${{ env.RELEASE_NAME }}.url
          
      - name: Upload files
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "cbld"
          name: Continuous Build
          files: |
            ./builds/LonkOS-${{ env.RELEASE_NAME }}.html
            ./builds/LonkOS-${{ env.RELEASE_NAME }}.url
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
